sudo: false

language: generic

jdk:
  - oraclejdk8

matrix:
    include:
        - python: 3.5
          os: linux
          dist: trusty
        - scal: 2.11.2
          os: linux
          dist: trusty
cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
script:
  - cd 20151214_challenge_245_easy_date_dilemma/java/date-dillema && gradle test
  - cd $TRAVIS_BUILD_DIR/20151214_challenge_245_easy_date_dilemma/scala/date-dillema && sbt test
